### ISSUE TITLE
Possible to use also TB Lists

### ISSUE THREAD

**Issue by damjang** [CherryDT/thunderbird-one-click-forward#1]
First I may thank you for this very useful add-on!
I have setup a list of 4 persons in my TB contacts. Can this list be used for fast forward? I try but for me don't work.
Thank you!

**Comment by CherryDT** [comment]
Good point!

This is fixed now in 1.0.2, should be published soon once Mozilla is done reviewing it. In the meantime you can directly install the XPI, if you want: https://addons.thunderbird.net/thunderbird/downloads/file/1026850/one_click_forward-1.0.2-tb.xpi?src=devhub

**Comment by damjang** [comment]
Thank you very mutch, work perfectly!
